site_name: Docs
site_url: https://maybesomedev.github.io/Roblox-Boids-Implementation/
repo_name: maybeSomeDev/Roblox-Boids-Implementation
repo_url: https://github.com/maybeSomeDev/Roblox-Boids-Implementation

dev_addr: 'localhost:5000'

extra_css:
  - extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  # [details/summary=] block https://facelessuser.github.io/pymdown-extensions/extensions/details/
  # Usage: ??? , ???+
  - pymdownx.details
  # same as .details but not collapsible https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  # Usage: !!!
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.superfences

theme:
  name: material
  logo: icon.png
  favicon: icon.png

  features:
    - navigation.tabs
    - content.code.copy

  palette:
      scheme: slate
  
nav:
  - Home:
    - Setup: index.md
    - Post: post.md

  - API:
    - API Reference: api.md
    - Data Types: data.md

  - Configs: configs.md
    